# 🟩 NumPy  
본격적으로 넘파이를 배워보자!  

- 분석용라이브러리  
- c언어  


In [1]:
import sys
print(sys.executable)


c:\Users\user\.conda\envs\sesacAI\python.exe


### 🟡 타입 변환

In [ ]:
import numpy as np

a = [1,2,3,4,5]
b = [2,4,6,8,10]

c = a + b
print(c)



# 머신러닝, 딥러닝 둘 다 취급하는 데이터 타입이 ndarray 타입이다.
a1 = np.array(a)   # 타입을 list -> ndarray 타입으로 변환 (c언어의 배열, 속도가 엄청 빠름)
print(a1, type(a1))

b1 = np.array(b)
print(b1, type(b1))

c1 = a1 + b1            # 수학의 벡터연산을 수행한다.
print(c1, type(c1))     # 스칼라연산 - 요소 하나씩 더하기
                        # 벡터연산 - 벡터 통째로 (배열 통쨰로 연산을 수행함 / for문 없이 연산을 수행함)





In [ ]:
import numpy as np


x = np.array([1,2,3,4,5,6,7,8,9,10])
y = 2*x + 3
print(y)



In [4]:
# 기초 통계

import numpy as np


print('평균', np.mean([1,2,3,4,5]))
print('중앙값', np.median([1,2,3,4,5]))
print('분산', np.var([1,2,3,4,5]))








평균 3.0
중앙값 3.0
분산 2.0


### 🟡 2차원 배열

In [11]:
# 행렬 연산

import numpy as np

# 수학적으로 행렬 (matrix)
m1 = np.array([[1,2], [3,4]])
m2 = np.array([[5,6], [7,8]])

"""
<생김새 그려보기>
1   2      5   6   =   1+5    2+6      6   8
3   4      7   8   =   3+7    4+8      10  12 
각각의 자리끼리 서로 계산을 해준다.
"""


# 행렬 덧셈
print('\n-----행렬 덧셈-----')
m3 = m1 + m2   # 행렬 덧셈
print(m3)

# 행렬 인덱싱
print('\n-----행렬 인덱싱-----')
print(m1[0,0]) # 1
print(m1[0,1]) # 2
print(m1[1,0]) # 3
print(m1[1,1]) # 4

# 행렬 슬라이싱
print('\n-----행렬 슬라이싱-----')
print(m1[0]) # [1,2]
print(m1[1]) # [3,4]  

# 행렬 연산 (곱셈, 벡터연산)
print('\n-----행렬 연산 (곱셈, 벡터연산)-----')
print(m1 * m2) # 행렬 곱셈 (각각의 자리끼리 곱셈)
print(m1.dot(m2)) # 행렬 곱셈 (벡터 연산)

# 요소의 크기
print('\n-----요소의 크기-----')
print (m1.shape) # (2,2)
row, col = m1.shape
print(row, col) # 2 2
print( m1.dtype) #데이터 타입 확인하기 - int32

# 행렬 요소 출력
print('\n-----행렬 요소 출력-----')
for i in range(0,row):
    for j in range(0,col):
        print(m1[i,j], ',', end='')
    print()








-----행렬 덧셈-----
[[ 6  8]
 [10 12]]

-----행렬 인덱싱-----
1
2
3
4

-----행렬 슬라이싱-----
[1 2]
[3 4]

-----행렬 연산 (곱셈, 벡터연산)-----
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]

-----요소의 크기-----
(2, 2)
2 2
int64

-----행렬 요소 출력-----
1 ,2 ,
3 ,4 ,


### 🟡 복사의 개념

In [15]:
import numpy as np

# 🟡 range 대신  =>  arange(시작값, 끝값, 증가값)
# for문이나 list 대신 사용할 수 있다.
print('\n-----arange-----')
print( np.arange(1,11))     # 1부터 10까지 1씩 증가
print( np.arange(0,10,0.1)) # 0부터 10까지 0.1씩 증가
print( np.arange(0,10,2))   # 0부터 10까지 2씩 증가


# 🟡 복사하기 - 얕은 복사
print('\n-----얕은 복사-----')
a = np.arange(1,11)
b = a  # 얕은 복사

a[0] = 100
print(a)
print(b)

# 🟡 복사하기 - 깊은 복사
print('\n-----깊은 복사-----')
c = a.copy() # 깊은 복사
c[0] = 100
print(a)
print(c)


# 🟡 얕은 복사와 깊은 복사의 차이점
# 얕은 복사는 원본 데이터를 복사하는 것이 아니라 참조를 복사하는 것이다.
# 깊은 복사는 원본 데이터를 복사하는 것이다.
# 얕은 복사는 원본 데이터를 변경하면 복사한 데이터도 변경된다.
# 깊은 복사는 원본 데이터를 변경하면 복사한 데이터는 변경되지 않는다.
# 얕은 복사는 메모리 사용량이 적다. (참조를 복사하기 때문에)
# 깊은 복사는 메모리 사용량이 많다. (원본 데이터를 복사하기 때문에)
# 얕은 복사는 원본 데이터를 변경하면 복사한 데이터도 변경된다.
# 깊은 복사는 원본 데이터를 변경하면 복사한 데이터는 변경되지 않는다.






-----arange-----
[ 1  2  3  4  5  6  7  8  9 10]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]
[0 2 4 6 8]

-----얕은 복사-----
[100   2   3   4   5   6   7   8   9  10]
[100   2   3   4   5   6   7   8   9  10]

-----깊은 복사-----
[100   2   3   4   5   6   7   8   9  10]
[100   2   3   4   5   6   7   8   9  10]

-----메모리 할당을 해서 요소의 값이 0이나 1로 채워진 ndarray 타입 만들기-----
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 🟡 특정값 채우기 및 random 함수

In [16]:

import numpy as np


# 🟡 메모리 할당을 해서 요소의 값이 0이나 1로 채워진 ndarray 타입 만들기
# N-dimensional array - 1차원부터 N차원까지 모든 형태의 배열
print('\n-----메모리 할당을 해서 요소의 값이 0이나 1로 채워진 ndarray 타입 만들기-----')
a = np.zeros(10) # 10개의 요소를 가진 1차원 배열 만들기
print(a)

b = np.zeros((3,4)) # 3x4 행렬 만들기 (3행 4열)  / 튜플로 만들어줘야 합니다.
print(b)

c = np.ones((3,4)) # 3x4 행렬 만들기 (3행 4열)  / 튜플로 만들어줘야 합니다.
print(c)




# 🟡 rand 함수
# 0부터 1사이의 랜덤 값을 생성
# 가우스분포(정규분포)를 따르는 랜덤 값을 생성
# 요소가 랜덤인 배열 또는 행렬을 생성할 때 사용

print('\n-----random 함수 사용-----')
print(np.random.rand(10))    # 10개의 요소를 가진 1차원 배열 만들기
print(np.random.rand(3,4))   # 3x4 행렬 만들기 (3행 4열)  / 튜플로 만들어줘야 합니다.
print(np.random.rand(3,4,5)) # 3x4x5 행렬 만들기 (3행 4열 5층)  / 튜플로 만들어줘야 합니다.


# 정수발생 np.random.randint(시작값, 끝값, 개수)  low ~ high-1 사이의 정수를 발생
print('\n-----random 정수발생-----')
print(np.random.randint(1,10)) # 1부터 10까지의 정수 발생 (기본 1개 발생)
print(np.random.randint(1,10,5)) # 1부터 10까지의 5개의 정수 발생
print(np.random.randint(1,10, (2,3))) # 2x3 행렬 만들기 (2행 3열)  / 튜플로 만들어줘야 합니다.








-----메모리 할당을 해서 요소의 값이 0이나 1로 채워진 ndarray 타입 만들기-----
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

-----random 함수 사용-----
[0.46971355 0.51477596 0.69382157 0.85393846 0.15911117 0.80636412
 0.97722836 0.5135888  0.34789808 0.77302665]
[[0.3247341  0.81755361 0.9147985  0.97907277]
 [0.46616134 0.55981787 0.2459734  0.62582478]
 [0.66060244 0.16154262 0.32810639 0.70901785]]
[[[0.91501489 0.82176781 0.47571233 0.05451424 0.74591572]
  [0.51199627 0.97737448 0.30641322 0.17301142 0.86475772]
  [0.03431794 0.82389632 0.07814125 0.16081099 0.43459342]
  [0.84441939 0.72396172 0.33133799 0.18312076 0.62954506]]

 [[0.80794125 0.61023359 0.45772738 0.22644783 0.1188529 ]
  [0.3987096  0.07033776 0.28743964 0.46919428 0.98856405]
  [0.79490911 0.3548846  0.09744829 0.68693302 0.28774897]
  [0.40384623 0.39146808 0.4265744  0.19244981 0.67012094]]

 [[0.45256261 0.83297533 0.99609985 0.48805029 0.57565128]
  [0.49

### 🟡 행렬의 차원 변환

In [18]:
# 행렬의 차원 변환

import numpy as np

# 차원변환
a = np.arange(10)
a = a.reshape(2,5)
print(a)

a = a.reshape(5,2)
print(a)






[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### 🟡 유연한 array 연산

In [21]:
# 유연한 array 연산

import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([2,4,6,8,10])

print( a+b )
print( a-b )
print( a*b )
print( a/b )


[ 3  6  9 12 15]
[-1 -2 -3 -4 -5]
[ 2  8 18 32 50]
[0.5 0.5 0.5 0.5 0.5]


### 🟡 np.array slicing

In [23]:
# 슬라이싱

import numpy as np

a = np.arange(20)
print(a)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
