# 🟩 NumPy  
본격적으로 넘파이를 배워보자!  

- 분석용라이브러리  
- c언어  


In [1]:
import sys
print(sys.executable)


c:\Users\user\.conda\envs\sesacAI\python.exe


### 🟡 np.array slicing

In [3]:
# 슬라이싱

import numpy as np

a = np.arange(20)
print('생성', a)

print(a[0])
print(a[1])
print(a[8])
print(a[9])
print(a[:10])  # 0부터 9까지    
print(a[10:])  # 10부터 19까지
print(a[::-1]) # 19부터 0까지
print(a[::-2]) # 19부터 0까지 2씩 감소
print(a[1:10:2]) # 1부터 9까지 2씩 증가
print(a[::2]) # 0부터 19까지 2씩 증가
print(a[1:3]) # 1부터 2까지
print(a[2:7])


생성 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
0
1
8
9
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[19 17 15 13 11  9  7  5  3  1]
[1 3 5 7 9]
[ 0  2  4  6  8 10 12 14 16 18]
[1 2]
[2 3 4 5 6]


### 🟡 조건식 (유연한 사용)

In [9]:
import numpy as np

x = np.arange(20)
print('생성',x)

# 조건식
print (x >= 10)  # [False, False, ... True, True]

# ❌ 파이썬의 리스트는 조건식이 적용되지 않는다.
# a = [1,2,3,4,5,6,7,8,9,10]
# print(a >= 5)

# 조건에 맞는 인덱스 값을 출력
print('----- 조건에 맞는 인덱스 값을 출력-----')
print( x[ [1,2,3,4,5 ] ]) # 1,2,3,4,5 인덱스 값을 출력
print( x[ x >= 10  ])     # 10 이상인 인덱스 값을 출력


# x 값이 짝수의 경우만 출력
print('-----짝수의 인덱스 값을 출력-----')
print( x[ x % 2 == 0  ]) # 짝수의 인덱스 값을 출력



# 3의 배수이면서 5의 배수인 것을 추축하고 싶다.
print('-----3의 배수이면서 5의 배수인 것을 추축하고 싶다.-----')
# 💥 python의 and 연산자는 numpy에서 & 연산자로 사용한다.
print( x[ (x % 3 == 0) & (x % 5 == 0)  ]) # 3의 배수이면서 5의 배수인 것을 추축하고 싶다.
# 다른 방법
print( x[ np.logical_and(x % 3 == 0, x % 5 == 0)  ]) # 3의 배수이면서 5의 배수인 것을 추축하고 싶다.


# 이건 뭐야?
x = np.array([1,2,3,4,5,6,7,8,9,10])
print( x[ [True, True, True, True, False, False] ])




생성 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[False False False False False False False False False False  True  True
  True  True  True  True  True  True  True  True]
----- 조건에 맞는 인덱스 값을 출력-----
[1 2 3 4 5]
[10 11 12 13 14 15 16 17 18 19]
-----짝수의 인덱스 값을 출력-----
[ 0  2  4  6  8 10 12 14 16 18]
-----3의 배수이면서 5의 배수인 것을 추축하고 싶다.-----
[ 0 15]
[ 0 15]


In [16]:
import numpy as np

# 2차원의 경우의 slicing
k = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]])

k2 = np.arange(1, 21)
k2 = k2.reshape(4,5)
print('k', k)
print('k2', k2)


print('------- 전부다 출력 ------')
print(k[:]) # 전부다
print('-------- 첫번째 행 출력 ------')
print(k[:1]) # 첫번째 행
print('-------- 첫번째 행, 두번째 행 출력 ------')
print(k[:2]) # 첫번째 행과 두번째 행
print('-------- 첫번째 행과 두번째 행과 세번째 행 출력 ------')
print(k[:3]) # 첫번째 행과 두번째 행과 세번째 행

print('------ 2칸씩 건너뛰면서 출력 -------')
print(k[::2]) # 2칸씩 건너뛰면서 출력
print('-------- 첫번째 행과 두번째 행의 첫번째 열과 두번째 열 출력 ------')
print(k[:2, :2]) # 첫번째 행과 두번째 행의 첫번째 열과 두번째 열
print('-------- 두번째 행과 세번째 행의 세번째 열과 네번째 열 출력 ------')
print(k[2:4, 3:5]) # 두번째 행과 세번째 행의 세번째 열과 네번째 열


# 🟡 numpy 배열 합하기
print('-------- 배열 합하기 ------')
a = np.array([1,2,3,4,5])
b = np.arrange(6, 11)
c = np.concatenate((a,b, np.arrange(11, 21)))
print(c)

c1 = np.array_split(c, 3)  # 3개의 배열로 나누기
print(c)
print(c1)
print(c1[0])
print(c1[1])
print(c1[2])



# 🟡 검색은 where를 사용한다.




k [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
k2 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
------- 전부다 출력 ------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
-------- 첫번째 행 출력 ------
[[1 2 3 4 5]]
-------- 첫번째 행, 두번째 행 출력 ------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
-------- 첫번째 행과 두번째 행과 세번째 행 출력 ------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
------ 2칸씩 건너뛰면서 출력 -------
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
-------- 첫번째 행과 두번째 행의 첫번째 열과 두번째 열 출력 ------
[[1 2]
 [6 7]]
-------- 두번째 행과 세번째 행의 세번째 열과 네번째 열 출력 ------
[[14 15]
 [19 20]]


### 🟡 정렬

In [ ]:
import numpy as np

# 🟡 정렬
c1 = np.random.randint(1, 100, 10 )  # 1부터 100까지의 랜덤한 10개의 숫자를 생성
print(c1)

c2 = np.sort(c1)  # 오름차순 정렬 후 새로운 배열을 생성하여 반환한 것을 c2로 정의의
print(c2)



### 🟡 최댓값, 최솟값

In [18]:
# argmax / argmin

import numpy as np

a= np.random.rand(5)  # 0부터 1까지의 랜덤한 5개의 숫자를 생성

print(a)

print('최대값과 최대값의 인덱스 :', np.max(a ), np.argmax(a))  # 최대값과 최대값의 인덱스

print('최소값과 최소값의 인덱스 :', np.min(a ), np.argmin(a))  # 최소값과 최소값의 인덱스



[0.4118938  0.41712108 0.40322791 0.75931618 0.92830576]
최대값과 최대값의 인덱스 : 0.9283057569648363 4
최소값과 최소값의 인덱스 : 0.4032279119029676 2


In [ ]:
# argmax / argmin

import numpy as np

# 랜덤값은 컴퓨터의 내부의 시계를 이용해서 추출하는데
# 보고서를 쓸 때 값이 계속 바뀌면 문제가 되는 경우가 있다.
# 고정시키고 싶을 때, seed값을 고정시키면 된다.

np.random.seed(1234)  # 1234라는 값을 고정시키면 랜덤값이 고정된다.
a = np.random.rand(5)  # 0부터 1까지의 랜덤한 5개의 숫자를 생성
print(a)
print('최대값과 최대값의 인덱스 :', np.max(a ), np.argmax(a))  # 최대값과 최대값의 인덱스


a = np.random.rand(5)  # 0부터 1까지의 랜덤한 5개의 숫자를 생성
print(a)
print('최대값과 최대값의 인덱스 :', np.max(a ), np.argmax(a))  # 최대값과 최대값의 인덱스
print('최소값과 최소값의 인덱스 :', np.min(a ), np.argmin(a))  # 최소값과 최소값의 인덱스



### ✏️ 가벼운 문제 풀어보기

- 문제 1 : 가우스분포에 따른 랜덤값을 5개씩 10개 생성해서 각 행마다 제일 큰 값하고 큰 값 위치 찾아서 출력하기

In [22]:
import numpy as np

a = np.random.rand(5)  # 0부터 1까지의 랜덤한 5개의 숫자를 생성
b = np.random.rand(5)  # 0부터 1까지의 랜덤한 5개의 숫자를 생성
# 이게 총 10개 생성했다고 생각함... ㄷㄷㄷ

c = np.array([a,b])  # 2차원 배열로 변환
        # 사실 이것보다 reshape를 사용하는 것이 더 좋음

print(c)

print('0인덱스의 최대값과 최대값 :', np.max(c[0]), np.argmax(c[0]))
print('1인덱스의 최대값과 최대값 :', np.max(c[1]), np.argmax(c[1]))




[[0.19679567 0.20353558 0.95151577 0.5424428  0.88226542]
 [0.50992394 0.11512456 0.31619353 0.15600304 0.27553635]]
최대값과 최대값의 인덱스 : 0.9515157708665859 2
최대값과 최대값의 인덱스 : 0.5099239400608303 0


In [27]:
# 정답

a = np.random.rand(50)  # 0부터 1까지의 랜덤한 50개의 숫자를 생성 / 이것은 1차원임
a = a.reshape(10,5)  # reshape 함수는 배열의 형태를 변경하는 함수 / 즉 차원을 변환함!!!

print(a)  # 10행 5열의 배열이 생성된 것을 알 수 있습니다!!!

for i in range(10):
    print(f'{i}행 :', a[i])
    print(f'{i}행의 최대값과 최대값의 인덱스 :', np.max(a[i]), np.argmax(a[i]))

[[0.22511175 0.87207083 0.14135986 0.75454185 0.0725995 ]
 [0.07744612 0.40545783 0.03915063 0.1860144  0.44753822]
 [0.25498569 0.67327581 0.7340452  0.84571726 0.55426511]
 [0.13447547 0.60444858 0.46516654 0.61889996 0.02625293]
 [0.85182489 0.28184982 0.0111526  0.52298682 0.79285035]
 [0.73105921 0.76668133 0.51175458 0.22828218 0.27507146]
 [0.94742477 0.6766965  0.4278558  0.15281175 0.52257153]
 [0.76183509 0.71338333 0.53628994 0.80403594 0.74877902]
 [0.15189576 0.74667967 0.4452283  0.26847166 0.14521847]
 [0.69831341 0.8663007  0.15983927 0.37156502 0.61204713]]
0행 : [0.22511175 0.87207083 0.14135986 0.75454185 0.0725995 ]
0행의 최대값과 최대값의 인덱스 : 0.8720708330264216 1
1행 : [0.07744612 0.40545783 0.03915063 0.1860144  0.44753822]
1행의 최대값과 최대값의 인덱스 : 0.44753821784580405 4
2행 : [0.25498569 0.67327581 0.7340452  0.84571726 0.55426511]
2행의 최대값과 최대값의 인덱스 : 0.8457172574248377 3
3행 : [0.13447547 0.60444858 0.46516654 0.61889996 0.02625293]
3행의 최대값과 최대값의 인덱스 : 0.6188999625335723 3
4행 : [

### 🟡 ndarray을 파일로 저장하고, 불러오기

In [28]:
import numpy as np

data = np.random.rand(5)
print(data)

# 파일 저장하기
np.save('datafile.npy', data) 
#파일확장자는 npy이다, 생략하면 무조건 npy를 부여한다  


# 빈 리스트 생성
data=[]  # 빈 리스트 생성
print(data) # 빈 리스트 출력


# 파일 불러오기
data = np.load('datafile.npy')  # 파일 불러오기
print(data)




[0.47744544 0.50803246 0.45269014 0.06376316 0.02799072]
[]
[0.47744544 0.50803246 0.45269014 0.06376316 0.02799072]


In [30]:
import numpy as np

print('--------- 파일 저장하기 ---------')
data1=np.arange(1,11)     # 1부터 10까지의 숫자를 생성
data2=np.random.rand(10)  # 0부터 1까지의 랜덤한 10개의 숫자를 생성
print(data1)
print(data2)

np.savez( 'data.npz', key1=data1, key2=data2) 
# 파일 확장자는 npz이다, key=값 쌍으로 전달, dintionary로 전달 시 저장.
# 함수명이 savez 이다. 파일 확장자는 npz이고, key=값 형태로 dictionary 저장한다.


# 파일 불러오기
print('--------- 파일 불러오기 ---------')
outfile = np.load('data.npz')  # 파일 불러오기
print(outfile.files)  # 파일 불러오기

data1 = outfile['key1']  # 파일 불러오기
data2 = outfile['key2']  # 파일 불러오기
print(data1, data2)




--------- 파일 저장하기 ---------
[ 1  2  3  4  5  6  7  8  9 10]
[0.51592366 0.02044793 0.93094749 0.4632431  0.01394468 0.24246264
 0.9473344  0.65800557 0.894914   0.89472753]
--------- 파일 불러오기 ---------
['key1', 'key2']
[ 1  2  3  4  5  6  7  8  9 10] [0.51592366 0.02044793 0.93094749 0.4632431  0.01394468 0.24246264
 0.9473344  0.65800557 0.894914   0.89472753]


### 🟡 linspace


numpy.linspace()는 지정한 시작값과 끝값 사이를 일정한 간격으로 나눠서, 원하는 개수만큼 숫자를 만들어주는 함수입니다.

예를 들어:

0부터 1까지 5개 숫자를 일정한 간격으로 나누면 → [0. , 0.25, 0.5, 0.75, 1.]
