# 🟩 module




```python

```

In [ ]:
# 🔥🔥🔥🔥🔥 mod1.py라는 파일을 하나 만들었다고 가정합니다.

def add(x, y):
  return x + y

def sub(x, y):
  return x - y


class Person:
  def __init__(self, name='', age=0):
    self.name = name
    self.age = age

  def print(self):
    print(f"name = {self.name} | age = {self.age}")

print( add(3,4) )
print( sub(3,4) )

p = Person('조승연', 10)
p.print()


name = 조승연 | age = 10


In [ ]:
# 🔥🔥🔥🔥🔥 다른 파일 useModule1.py 라는 파일을 또 하나 만듭니다.
# ✅ import mod1 #import 해줍니다.
# (여기는 jupyter라서 안 만들겠습니다..)

# print( mod1.add(3, 4))  # ✅ 원래는 import 문으로 이렇게 써야합니다.
print( add(3, 4))
# print( mod1.sub(3, 4))  # ✅ 원래는 import 문으로 이렇게 써야합니다.
print( sub(3, 4))


# -----------------------------------------------
# 모듈은 내부에 내장변수로 __name__이라는 변수가 있다.
# 이 변수는 이 파일이 직접 실행될 때는 __main__으로 오고 
# import되어서 실행될 때는 파일명(mod1)으로 온다.
# print('모듈명 : ', __name__)
if __name__ == '__main__':
  print( add(3,4) )
  print( sub(3,4) )

# p2 = mod1.Person('윤하', 44) # ✅ 원래는 import 문으로 이렇게 써야합니다.
p2 = Person('윤하', 44) 
p2.print()

7
-1
7
-1
name = 윤하 | age = 44


In [ ]:
# 🔥🔥🔥🔥🔥 import문에 alias를 통해 다른 이름으로 부를 수 있다.  as md
# import mod1 as md    # 모듈명이 길 경우 aliasing 다른 이름으로 부를 수 있다.

# print( ✅md.add(3, 4))  # ✅ 원래는 import 문으로 이렇게 써야합니다.
print( add(3, 4))
# print( ✅md.sub(3, 4))  # ✅ 원래는 import 문으로 이렇게 써야합니다.
print( sub(3, 4))

# p2 = ✅md.Person('윤하', 44) # ✅ 원래는 import 문으로 이렇게 써야합니다.
p2 = Person('윤하', 44)
p2.print()

In [ ]:
# 🔥🔥🔥🔥🔥 파일명을 쓰기 싫고 마치 내 함수처럼 쓰고 싶다면
# form mod1 import add, sub   # ✅ 이렇게 작성을 해줍니다.
print( add(3, 4))  # ✅ 이대로 쓸 수 있습니다.
print( sub(3, 4))  # ✅ 이대로 쓸 수 있습니다.

p3 = Person('조이', 24)
p3.print()


---
### 🟡 numpy 맛보기

In [ ]:
# 수학라이브러리 -> 머신러닝의 경우 무조건 numpy 타입으로 전환해야 한다.
import numpy as np 

a = [1,2,3,4,5,6,7,8,9,10]
b = [x * 2 for x in a]
c = a+b  # 배열을 합쳐버린다.

print(a)
print(b)
print(c)   # 배열을 합쳐버린다.

print('---------------------------------')


a1 = np.array(a)
b1 = 2 * a1
c1 = a1 + b1  # 서로의 인덱스자리마다 더하기를 시행합니다.
print(a1)
print(b1)
print(c1) # 서로의 인덱스자리마다 더하기를 시행합니다.



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
---------------------------------
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[ 3  6  9 12 15 18 21 24 27 30]


- 스칼라 연산 
  - 1:1 연산, 대부분은 프로그래밍 언어가 이걸 지원
  - 다:다 연산은 for문을 써서 해야했다.

- 통계분석용 언어들은 수학에 가깝게 벡터연산을 지원한다.
- 벡터연산 - 다대다 연산을 한다. R, python의 numpy, pandas 라이브러리들이 벡터연산을 지원한다.