<br>

## 🟢 sklearn.datasets - load_digits (이미지분류)

- sklearn에서 load_digits() -> 손으로 쓴 숫자 맞추기
- 이미지 => 디지털화하는 과정에 흑백은 2차원 배열, 칼라는 3차원 배열임
- 이미지가 10장이 있고, 각 이미지 크기가 150 by 150
- 10 150*150이 특성의 개수가 된다.
- 이미지 => numpy배열로 바꿔야 : 파이썬이 PIL 라이브러리로 제공된다.


In [ ]:
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
import numpy as np

# ===================================================
# 데이터 불러오기
digits = load_digits()
x = digits.data
y = digits.target
print(f"x.shape : {x.shape}")  # 1797개의 이미지, 64개의 특성
print(f"y.shape : {y.shape}")  # 1797개의 타겟값
print(f"x[0] : {x[0]}")  # 0~16 사이의 값을 가진다.
print(f"y[0] : {y[0]}")  # 0~9 사이의 값을 가진다.

# 이미지 확인
print(digits.images[:10]) # numpy 2d -> 1d로 바꿔서 data로 준거고, 월래 데이너
images = digits.images

# plt.figure(figsize=(10, 4))  # 이미지 크기 조절 / 차트의 크기
# plt.imshow(images[0], cmap="gray_r")  # gray_r : 흑백 이미지
# plt.show()

# 이미지를 여러개 출력하려면 화면 분할을 해야한다.
plt.figure(figsize=(10, 4))  # 화면 전체 크기를 지정하고 나서 작게 나누려면 sublot 함수를 사용한다.
# 2 by 5 쪼개면 10개의 화면이 만들어지고, 각 분할 위치에 번호가 붙느다.
# 1 2 3 4 5
# 6 7 8 9 10
for i in range(10):
    plt.subplot(2, 5, i + 1)
    plt.imshow(images[i], cmap="gray_r", interpolation="nearest")  # interpolation : 보간법
    plt.title(f"label : {y[i]}")

# 이쁘게 다시 정리해줘!!!
plt.tight_layout()  # 이쁘게 다시 정리해라
plt.suptitle("첫 10개 Digits 이미지", y=1.05, fontsize=16)
# y는 제목이 출력될 위치를 말하는데 y=0 이면 아래쪽 y=1 이면 위쪽 1.05는 영역 바깥쪽에 놓으라는 의미임
plt.show()


x.shape : (1797, 64)
y.shape : (1797,)
x[0] : [ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
 15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
  0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
  0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]
y[0] : 0
[[[ 0.  0.  5. 13.  9.  1.  0.  0.]
  [ 0.  0. 13. 15. 10. 15.  5.  0.]
  [ 0.  3. 15.  2.  0. 11.  8.  0.]
  [ 0.  4. 12.  0.  0.  8.  8.  0.]
  [ 0.  5.  8.  0.  0.  9.  8.  0.]
  [ 0.  4. 11.  0.  1. 12.  7.  0.]
  [ 0.  2. 14.  5. 10. 12.  0.  0.]
  [ 0.  0.  6. 13. 10.  0.  0.  0.]]

 [[ 0.  0.  0. 12. 13.  5.  0.  0.]
  [ 0.  0.  0. 11. 16.  9.  0.  0.]
  [ 0.  0.  3. 15. 16.  6.  0.  0.]
  [ 0.  7. 15. 16. 16.  2.  0.  0.]
  [ 0.  0.  1. 16. 16.  3.  0.  0.]
  [ 0.  0.  1. 16. 16.  6.  0.  0.]
  [ 0.  0.  1. 16. 16.  6.  0.  0.]
  [ 0.  0.  0. 11. 16. 10.  0.  0.]]

 [[ 0.  0.  0.  4. 15. 12.  0.  0.]
  [ 0.  0.  3. 16. 15. 14.  0.  0.]
  [ 0.  0.  8. 13.  8. 16.  0.  

### 🟡 이미지 크기가 8 by 8이라는 의미 설명

In [8]:
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
import numpy as np


# 이미지 크기가 8 by 8이라는 의미 설명
print("=" * 50)
print("이미지 크기 8 by 8의 의미")
print("=" * 50)

print(f"원본 이미지 형태: {images[0].shape}")  # (8, 8) - 2차원 배열
print(f"데이터 변환 후 형태: {x[0].shape}")     # (64,) - 1차원 배열로 변환

print("\n[설명]")
print("1. 8 by 8 = 8행 8열의 픽셀로 구성된 이미지")
print("2. 총 픽셀 수: 8 × 8 = 64개")
print("3. 각 픽셀은 0~16 사이의 그레이스케일 값")
print("4. x 데이터는 2차원(8,8) → 1차원(64)으로 변환된 형태")

# 실제 이미지 데이터 확인
print(f"\n첫 번째 이미지의 원본 2차원 형태:")
print(images[0])

print(f"\n첫 번째 이미지의 1차원 변환 형태:")
print(x[0])

print(f"\n64개 특성의 의미: 각 픽셀의 밝기값 (0=검은색, 16=흰색)")



이미지 크기 8 by 8의 의미
원본 이미지 형태: (8, 8)
데이터 변환 후 형태: (64,)

[설명]
1. 8 by 8 = 8행 8열의 픽셀로 구성된 이미지
2. 총 픽셀 수: 8 × 8 = 64개
3. 각 픽셀은 0~16 사이의 그레이스케일 값
4. x 데이터는 2차원(8,8) → 1차원(64)으로 변환된 형태

첫 번째 이미지의 원본 2차원 형태:
[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]

첫 번째 이미지의 1차원 변환 형태:
[ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
 15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
  0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
  0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]

64개 특성의 의미: 각 픽셀의 밝기값 (0=검은색, 16=흰색)


In [13]:
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
import numpy as np

# ===================================================
# 데이터 불러오기
digits = load_digits()
x = digits.data
y = digits.target
print(f"x.shape : {x.shape}")  # 1797개의 이미지, 64개의 특성
print(f"y.shape : {y.shape}")  # 1797개의 타겟값
print(f"x[0] : {x[0]}")  # 0~16 사이의 값을 가진다.
print(f"y[0] : {y[0]}")  # 0~9 사이의 값을 가진다.

# 이미지 확인
print(digits.images[:10]) # numpy 2d -> 1d로 바꿔서 data로 준거고, 월래 데이너
images = digits.images
# plt.figure(figsize=(10, 4))  # 이미지 크기 조절 / 차트의 크기
# plt.imshow(images[0], cmap="gray_r")  # gray_r : 흑백 이미지
# plt.show()

# ===================================================
# 이미지를 여러개 출력하려면 화면 분할을 해야한다.
def drawNumbers():  # 마지막으로 함수 만들어서 빼놓기!!!!
    plt.figure(figsize=(10, 4))  # 화면 전체 크기를 지정하고 나서 작게 나누려면 sublot 함수를 사용한다.
    # 2 by 5 쪼개면 10개의 화면이 만들어지고, 각 분할 위치에 번호가 붙느다.
    # 1 2 3 4 5
    # 6 7 8 9 10
    for i in range(10):
        plt.subplot(2, 5, i + 1)
        plt.imshow(images[i], cmap="gray_r", interpolation="nearest")  # interpolation : 보간법
        plt.title(f"label : {y[i]}")

    # 이쁘게 다시 정리해줘!!!
    plt.tight_layout()  # 이쁘게 다시 정리해라
    plt.suptitle("첫 10개 Digits 이미지", y=1.05, fontsize=16)
    # y는 제목이 출력될 위치를 말하는데 y=0 이면 아래쪽 y=1 이면 위쪽 1.05는 영역 바깥쪽에 놓으라는 의미임
    plt.show()


# ===================================================
# 이미지 크기 자체는 8 by 8  ->  1차원으로 바꾸니까 64개의 특성
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=1, test_size=0.3)


# ===================================================
# 로지스틱
from sklearn.linear_model import LogisticRegression  # 분류
model = LogisticRegression(
        max_iter=5000,      # 최대 반복 횟수    
        random_state=0,     # 랜덤 시드
        solver="liblinear", # 최적화 알고리즘
        multi_class="auto"  # 다중 클래스 분류 방법
    )
# solver : 최적화 알고리즘
# multi_class : 다중 클래스 분류 방법
# max_iter : 계수 찾아갈 때 학습을 얼마나 반복할까를 지정하는 것것
model.fit(x_train, y_train)
print(f"\n\n로지스틱 모델 훈련 정확도 : {model.score(x_train, y_train)}")
print(f"로지스틱 모델 테스트 정확도 : {model.score(x_test, y_test)}")

# ===================================================
# Knn이웃 
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_train, y_train)
print("knn 이웃")
print("훈련셋", model.score(x_train, y_train))
print("테스트셋", model.score(x_test, y_test))

# ===================================================
# 의사결정트리 
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth=5)
model.fit(x_train, y_train)
print("DecisionTreeClassifier")
print("훈련셋", model.score(x_train, y_train))
print("테스트셋", model.score(x_test, y_test))

# ===================================================
# 랜덤포레스트
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(max_depth=4, n_estimators=100, random_state=0)
model.fit(x_train, y_train)
print("RandomForestClassifier")
print("훈련셋", model.score(x_train, y_train))
print("테스트셋", model.score(x_test, y_test))

# ===================================================
# 그라디언트부스팅  
from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier(max_depth=4, n_estimators=100, random_state=0, 
                                   learning_rate=0.1  )
model.fit(x_train, y_train)
print("GradientBoostingClassifier")
print("훈련셋", model.score(x_train, y_train))
print("테스트셋", model.score(x_test, y_test))




x.shape : (1797, 64)
y.shape : (1797,)
x[0] : [ 0.  0.  5. 13.  9.  1.  0.  0.  0.  0. 13. 15. 10. 15.  5.  0.  0.  3.
 15.  2.  0. 11.  8.  0.  0.  4. 12.  0.  0.  8.  8.  0.  0.  5.  8.  0.
  0.  9.  8.  0.  0.  4. 11.  0.  1. 12.  7.  0.  0.  2. 14.  5. 10. 12.
  0.  0.  0.  0.  6. 13. 10.  0.  0.  0.]
y[0] : 0
[[[ 0.  0.  5. 13.  9.  1.  0.  0.]
  [ 0.  0. 13. 15. 10. 15.  5.  0.]
  [ 0.  3. 15.  2.  0. 11.  8.  0.]
  [ 0.  4. 12.  0.  0.  8.  8.  0.]
  [ 0.  5.  8.  0.  0.  9.  8.  0.]
  [ 0.  4. 11.  0.  1. 12.  7.  0.]
  [ 0.  2. 14.  5. 10. 12.  0.  0.]
  [ 0.  0.  6. 13. 10.  0.  0.  0.]]

 [[ 0.  0.  0. 12. 13.  5.  0.  0.]
  [ 0.  0.  0. 11. 16.  9.  0.  0.]
  [ 0.  0.  3. 15. 16.  6.  0.  0.]
  [ 0.  7. 15. 16. 16.  2.  0.  0.]
  [ 0.  0.  1. 16. 16.  3.  0.  0.]
  [ 0.  0.  1. 16. 16.  6.  0.  0.]
  [ 0.  0.  1. 16. 16.  6.  0.  0.]
  [ 0.  0.  0. 11. 16. 10.  0.  0.]]

 [[ 0.  0.  0.  4. 15. 12.  0.  0.]
  [ 0.  0.  3. 16. 15. 14.  0.  0.]
  [ 0.  0.  8. 13.  8. 16.  0.  

c:\Users\user\.conda\envs\sesacAI\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


RandomForestClassifier
훈련셋 0.9387430389817024
테스트셋 0.937037037037037
GradientBoostingClassifier
훈련셋 1.0
테스트셋 0.9574074074074074
